### ISSUE TITLE
Error on initialization for version 7.2.1

### ISSUE THREAD

**Issue by niksy** [csstools/postcss-plugins#153]
### Bug description

Running latest version (7.2.1) produces following error in console:

```sh
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ({PATH}/node_modules/postcss-preset-env/dist/index.cjs:1:328)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

### Plugin version

7.2.1

### Node Version

12.22.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@niksy Can you share any details on how you invoke postcss?

**Comment by romainmenke** [comment]
Update, can replicate in node 12 :

https://github.com/csstools/postcss-plugins/runs/4787847190?check_suite_focus=true

**Comment by jjavierdguezas** [comment]
This is happening to me too just now with a cra app (last version)
`Loading PostCSS "postcss-preset-env" plugin failed: Unexpected token '.'`

**Comment by Antonio-Laguna** [comment]
Releasing a new version, tests are now passing: https://github.com/csstools/postcss-plugins/runs/4788325173?check_suite_focus=true

**Comment by Antonio-Laguna** [comment]
Released with 7.2.2,

@jjavierdguezas and @niksy could you review on your ends?

**Comment by jjavierdguezas** [comment]
> Released with 7.2.2,
> 
> @jjavierdguezas and @niksy could you review on your ends?

working now, thanks!

**Comment by romainmenke** [comment]
Thank you for reporting this!

**Comment by Queen-esther01** [comment]
I solved this error by updating tailwindcss and postcss
