### ISSUE TITLE
Replace Autoprefixer browsers option to Browserslist config

### ISSUE THREAD

**Issue by raphael10-collab** [csstools/postcss-plugins#385]
### Bug description

    (base) raphy@pc:~/Raphy-Template$ yarn start
    yarn run v1.22.18
    $ yarn run build && ELECTRON_DISABLE_SECURITY_WARNINGS=true electron ./dist/main/main.js
    $ npx webpack --config ./webpack.config.js
    
      Replace Autoprefixer browsers option to Browserslist config.
      Use browserslist key in package.json or .browserslistrc file.
    
      Using browsers option can cause errors. Browserslist config can
      be used for Babel, Autoprefixer, postcss-normalize and other tools.
    
      If you really need to use option, rename it to overrideBrowserslist.
    
      Learn more at:
      https://github.com/browserslist/browserslist#readme
      https://twitter.com/browserslist
    
    
    asset main.js 11.7 MiB [compared for emit] (name: main)
    runtime modules 793 bytes 4 modules
    javascript modules 8.74 MiB
      modules by path ./node_modules/ 8.68 MiB
        cacheable modules 8.67 MiB 1456 modules
        optional modules 3.24 KiB [optional] 3 modules
      modules by path ./src/ 59 KiB 14 modules
      + 28 modules
    json modules 1.19 MiB
      modules by path ./node_modules/har-schema/lib/ 6.93 KiB 18 modules
      modules by path ./node_modules/cheerio/ 96.9 KiB 16 modules
      modules by path ./node_modules/@postlight/mercury-parser/ 261 KiB 9 modules
      modules by path ./node_modules/iconv-lite/ 86.7 KiB 8 modules
      modules by path ./node_modules/ajv/lib/ 5.58 KiB 3 modules
      modules by path ./node_modules/whatwg-encoding/lib/ 5.33 KiB 2 modules
      + 9 modules
    
    WARNING in ./node_modules/jsdom/lib/jsdom/utils.js 186:21-40
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/jsdom/lib/jsdom/browser/Window.js 8:26-45
     @ ./node_modules/jsdom/lib/api.js 14:15-51
     @ ./node_modules/turndown/lib/turndown.es.js 527:16-38
     @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 11:38-57
     @ ./src/main/main.ts 52:41-77
    
    WARNING in ./node_modules/parse5/lib/index.js 55:23-49
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/jsdom/lib/jsdom/browser/domtohtml.js 2:15-32
     @ ./node_modules/jsdom/lib/api.js 15:22-61
     @ ./node_modules/turndown/lib/turndown.es.js 527:16-38
     @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 11:38-57
     @ ./src/main/main.ts 52:41-77
    
    2 warnings have detailed information that is not shown.
    Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
    
    webpack 5.72.0 compiled with 2 warnings in 41660 ms
    
    assets by status 394 bytes [cached] 5 assets
    assets by path lib/pdfjs-dist/web/ 3.78 MiB 342 assets
    assets by path assets/ 1.62 MiB 51 assets
    assets by path *.js 36.4 MiB 24 assets
    assets by path *.html 35.9 KiB 14 assets
    assets by path dist/assets/pics/pics/ 6.09 KiB
      assets by chunk 3.34 KiB (auxiliary name: app_G) 3 assets
      assets by chunk 2.75 KiB (auxiliary name: app_webpdf) 2 assets
    assets by path ../ 28.4 MiB
      asset ../ort-wasm-simd-threadedwasm 7.42 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm] [copied]
      + 3 assets
    assets by path lib/pdfjs-dist/build/*.js 2.3 MiB
      asset lib/pdfjs-dist/build/pdf.worker.js 1.32 MiB [compared for emit] [from: src/lib/pdfjs-dist/build/pdf.worker.js] [copied]
      + 2 assets
    + 5 assets
    orphan modules 278 KiB [orphan] 151 modules
    runtime modules 29.2 KiB 121 modules
    modules by path ./node_modules/ 12.2 MiB (javascript) 158 bytes (asset)
      javascript modules 12.2 MiB 2424 modules
      asset modules 84 bytes (javascript) 158 bytes (asset)
        ./node_modules/react-pdf-highlighter/node_modules/pdfjs-dist/web/images/shadow.png 42 bytes (javascript) 76 bytes (asset) [built] [code generated]
        ./node_modules/react-pdf-highlighter/node_modules/pdfjs-dist/web/images/loading-icon.gif 42 bytes (javascript) 82 bytes (asset) [built] [code generated]
    modules by path ./src/ 553 KiB (javascript) 236 bytes (asset)
      javascript modules 553 KiB 89 modules
      asset modules 126 bytes (javascript) 236 bytes (asset) 3 modules
    modules by mime type image/png 546 bytes
      data:image/png;base64,iVBORw0KGgoAAAAN.. 222 bytes [built] [code generated]
      data:image/png;base64,iVBORw0KGgoAAAAN.. 324 bytes [built] [code generated]
    + 6 modules
    webpack 5.72.0 compiled successfully in 41896 ms
    app.getPath('userData'):  /home/raphy/raphy-template
    process.cwd():  /home/raphy/Raphy-Template
    path.dirname(__filename):  /home/raphy/Raphy-Template/dist/main
    path.basename(path.dirname(__filename)):  main
    path.parse(dirname_path):  {
      root: '/',
      dir: '/home/raphy/Raphy-Template/dist',
      base: 'main',
      ext: '',
      name: 'main'
    }

### Source CSS

@tailwind base;

@tailwind components;

@tailwind utilities;

html,
body,
#app {
    min-height: 100vh;
}

div[role='menu'] {
    outline: none;
}

div[role='menuitem'] {
    outline: none;
}

input:focus {
    outline: none;
}

[role='button']:focus {
    outline: none;
}

[role='menuitemradio']:focus {
    outline: none;
}

.thin-scroll {
    @apply overflow-y-scroll;
}

.thin-scroll::-webkit-scrollbar {
    @apply bg-transparent w-2;
}

.thin-scroll::-webkit-scrollbar-thumb {
    @apply bg-gray-500 rounded-lg border-4 border-transparent bg-clip-content;
}

.rss-item {
    @apply leading-8 text-gray-300 flex items-center justify-between cursor-pointer px-3 py-2;
}

.rss-item.active {
    @apply bg-gray-600;
}

### Expected CSS

None

### Actual CSS

None

### Extra config

`webpack.config.js` : 

const postcss = require('postcss')
const postcssPresetEnv = require('postcss-preset-env')

        {
          test: /\.pcss$/,
          use: [
              { // https://github.com/webpack-contrib/postcss-loader#getting-started
                  loader: 'postcss-loader',
                  options: {
                      //config: {
                        //path: `${__dirname}/postcss.config.js`,
                      //},
                     postcssOptions: {
                        syntax: 'postcss-scss',
                        plugins: [
                          //"postcss-preset-env", // https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env
                          postcssPresetEnv({ browsers: 'defaults' })
                        ],
                      },
                  },
              },
          ],
        },

### Plugin version

"postcss-preset-env": "^7.5.0"

### Node Version

v16.15.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @raphael10-collab 

This was updated in postcss-preset-env 3 years ago :

<img width="1283" alt="Screenshot 2022-05-19 at 14 10 20" src="https://user-images.githubusercontent.com/11521496/169290253-3b013c32-cfd3-4302-bcc2-a681da946964.png">

We only use `overrideBrowserslist` as required by autoprefixer.

Can you verify the postcss-preset-env version you are using and if no other plugin or tool is adding autoprefixer?

**Comment by raphael10-collab** [comment]
Hi @romainmenke !

I realized that it was installed `autoprefixer`

But after removing it , still get : 

      Replace Autoprefixer browsers option to Browserslist config.
      Use browserslist key in package.json or .browserslistrc file.
    
      Using browsers option can cause errors. Browserslist config can
      be used for Babel, Autoprefixer, postcss-normalize and other tools.
    
      If you really need to use option, rename it to overrideBrowserslist.
    
      Learn more at:
      https://github.com/browserslist/browserslist#readme
      https://twitter.com/browserslist

May be one of these packages might be the cause?

    "devDependencies":
        "postcss-scss": "^4.0.4",
        "copy-webpack-plugin": "^7.0.0",
        "css-minimizer-webpack-plugin": "^1.2.0",
        "mini-css-extract-plugin": "^1.3.9",
        "postcss-flexbugs-fixes": "^5.0.2",
        "postcss-loader": "^7.0.0",
        "postcss-preset-env": "^7.5.0",
        "webpack": "^5.23.0",
        "webpack-bundle-analyzer": "^4.4.0",
        "webpack-cli": "^4.5.0"
        "postcss-scss": "^4.0.4"

**Comment by raphael10-collab** [comment]
With : 

    //const postcssPresetEnv = require('postcss-preset-env')

        {
          test: /\.pcss$/,
          use: [
              //{
                  //loader: 'style-loader',
              //},
              //{
                  //loader: 'css-loader',
                  //options: {
                      //sourceMap: true,
                  //},
              //},
              { // https://github.com/webpack-contrib/postcss-loader#getting-started
                  loader: 'postcss-loader',
                  options: {
                      //config: {
                        //path: `${__dirname}/postcss.config.js`,
                      //},
                     postcssOptions: {
                        syntax: 'postcss-scss',
                        plugins: [
                          "postcss-preset-env", // https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env
                          //postcssPresetEnv({ browserslist: 'defaults' })
                        ],
                      },
                      //sourceMap: true,
                  },
              },
          ],
        },

the warning still appears

But it appears also when commenting `postcss-preset-env`  in `webpack.config.js` :  

    const path = require('path');
    const cwd = process.cwd();
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const CopyPlugin = require("copy-webpack-plugin");
    const MiniCssExtractPlugin = require('mini-css-extract-plugin');
    const webpack = require('webpack');
    const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
    const postcss = require('postcss')


        {
          test: /\.pcss$/,
          use: [
              //{
                  //loader: 'style-loader',
              //},
              //{
                  //loader: 'css-loader',
                  //options: {
                      //sourceMap: true,
                  //},
              //},
              { // https://github.com/webpack-contrib/postcss-loader#getting-started
                  loader: 'postcss-loader',
                  options: {
                      //config: {
                        //path: `${__dirname}/postcss.config.js`,
                      //},
                     postcssOptions: {
                        syntax: 'postcss-scss',
                        plugins: [
                          //"postcss-preset-env", // https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env
                          //postcssPresetEnv({ browserslist: 'defaults' })
                        ],
                      },
                      //sourceMap: true,
                  },
              },
          ],
        },

So... what could be the cause ?

**Comment by romainmenke** [comment]
From the output of `npm why` I would say that `react-scripts` is doing this.

Unfortunately I do not know this package, so I can't say anything about this :/

**Comment by raphael10-collab** [comment]
I removed `react-scripts`:

    (base) raphy@pc:~/Raphy-Template$ npm why autoprefixer
    autoprefixer@10.4.7 dev
    node_modules/autoprefixer
      autoprefixer@"^10.4.6" from postcss-preset-env@7.5.0
      node_modules/postcss-preset-env
        dev postcss-preset-env@"^7.5.0" from the root project

But still get the warning : 

    (base) raphy@pc:~/Raphy-Template$ yarn start
    yarn run v1.22.18
    $ yarn run build && ELECTRON_DISABLE_SECURITY_WARNINGS=true electron ./dist/main/main.js
    $ npx webpack --config ./webpack.config.js
    
      Replace Autoprefixer browsers option to Browserslist config.
      Use browserslist key in package.json or .browserslistrc file.
    
      Using browsers option can cause errors. Browserslist config can
      be used for Babel, Autoprefixer, postcss-normalize and other tools.
    
      If you really need to use option, rename it to overrideBrowserslist.
    
      Learn more at:
      https://github.com/browserslist/browserslist#readme
      https://twitter.com/browserslist

**Comment by romainmenke** [comment]
And if you also completely remove `postcss-preset-env`?
Is there then still something requiring `autoprefixer`?

**Comment by romainmenke** [comment]
Very weird 🤔

**Comment by raphael10-collab** [comment]
I tried to run the app after having removed `postcss-preset-env` : 

    (base) raphy@pc:~/Raphy-Template$ yarn start
    yarn run v1.22.18
    $ yarn run build && ELECTRON_DISABLE_SECURITY_WARNINGS=true electron ./dist/main/main.js
    $ npx webpack --config ./webpack.config.js
    asset main.js 11.7 MiB [compared for emit] (name: main)
    runtime modules 793 bytes 4 modules
    javascript modules 8.72 MiB
      modules by path ./node_modules/ 8.66 MiB
        cacheable modules 8.66 MiB 1452 modules
        optional modules 3.24 KiB [optional] 3 modules
      modules by path ./src/ 59 KiB 14 modules
      + 28 modules
    json modules 1.19 MiB
      modules by path ./node_modules/har-schema/lib/ 6.93 KiB 18 modules
      modules by path ./node_modules/cheerio/ 96.9 KiB 16 modules
      modules by path ./node_modules/@postlight/mercury-parser/ 261 KiB 9 modules
      modules by path ./node_modules/iconv-lite/ 86.7 KiB 8 modules
      modules by path ./node_modules/ajv/lib/ 5.58 KiB 3 modules
      modules by path ./node_modules/whatwg-encoding/lib/ 5.33 KiB 2 modules
      + 9 modules
    
    WARNING in ./node_modules/jsdom/lib/jsdom/utils.js 186:21-40
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/jsdom/lib/jsdom/browser/Window.js 8:26-45
     @ ./node_modules/jsdom/lib/api.js 14:15-51
     @ ./node_modules/turndown/lib/turndown.es.js 527:16-38
     @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 11:38-57
     @ ./src/main/main.ts 52:41-77
    
    WARNING in ./node_modules/parse5/lib/index.js 55:23-49
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/jsdom/lib/jsdom/browser/domtohtml.js 2:15-32
     @ ./node_modules/jsdom/lib/api.js 15:22-61
     @ ./node_modules/turndown/lib/turndown.es.js 527:16-38
     @ ./node_modules/@postlight/mercury-parser/dist/mercury.js 11:38-57
     @ ./src/main/main.ts 52:41-77
    
    2 warnings have detailed information that is not shown.
    Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
    
    webpack 5.72.0 compiled with 2 warnings in 29458 ms
    
    assets by status 394 bytes [cached] 5 assets
    assets by path lib/pdfjs-dist/web/ 3.78 MiB 342 assets
    assets by path assets/ 1.62 MiB 51 assets
    assets by path *.js 36.4 MiB 24 assets
    assets by path *.html 35.9 KiB 14 assets
    assets by path dist/assets/pics/pics/ 6.09 KiB
      assets by chunk 3.34 KiB (auxiliary name: app_G) 3 assets
      assets by chunk 2.75 KiB (auxiliary name: app_webpdf) 2 assets
    assets by path ../ 28.4 MiB
      asset ../ort-wasm-simd-threadedwasm 7.42 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm] [copied]
      + 3 assets
    assets by path lib/pdfjs-dist/build/*.js 2.3 MiB
      asset lib/pdfjs-dist/build/pdf.worker.js 1.32 MiB [compared for emit] [from: src/lib/pdfjs-dist/build/pdf.worker.js] [copied]
      + 2 assets
    + 5 assets
    orphan modules 286 KiB [orphan] 153 modules
    runtime modules 29.2 KiB 121 modules
    modules by path ./node_modules/ 12.2 MiB (javascript) 158 bytes (asset)
      javascript modules 12.2 MiB 2424 modules
      asset modules 84 bytes (javascript) 158 bytes (asset)
        ./node_modules/react-pdf-highlighter/node_modules/pdfjs-dist/web/images/shadow.png 42 bytes (javascript) 76 bytes (asset) [built] [code generated]
        ./node_modules/react-pdf-highlighter/node_modules/pdfjs-dist/web/images/loading-icon.gif 42 bytes (javascript) 82 bytes (asset) [built] [code generated]
    modules by path ./src/ 553 KiB (javascript) 236 bytes (asset)
      javascript modules 553 KiB 89 modules
      asset modules 126 bytes (javascript) 236 bytes (asset) 3 modules
    modules by mime type image/png 546 bytes
      data:image/png;base64,iVBORw0KGgoAAAAN.. 222 bytes [built] [code generated]
      data:image/png;base64,iVBORw0KGgoAAAAN.. 324 bytes [built] [code generated]
    + 6 modules
    
    ERROR in ./src/assets/css/rssfeeds/app.pcss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./src/assets/css/rssfeeds/app.pcss)
    Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
    Loading PostCSS "autoprefixer" plugin failed: Cannot find module 'autoprefixer'
    Require stack:
    - /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/utils.js
    - /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/index.js
    - /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/cjs.js
    - /home/raphy/Raphy-Template/node_modules/loader-runner/lib/loadLoader.js
    - /home/raphy/Raphy-Template/node_modules/loader-runner/lib/LoaderRunner.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/NormalModuleFactory.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/Compiler.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/webpack.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/index.js
    - /home/raphy/Raphy-Template/node_modules/webpack-cli/lib/webpack-cli.js
    - /home/raphy/Raphy-Template/node_modules/webpack-cli/lib/bootstrap.js
    - /home/raphy/Raphy-Template/node_modules/webpack-cli/bin/cli.js
    - /home/raphy/Raphy-Template/node_modules/webpack/bin/webpack.js
    
    (@/home/raphy/Raphy-Template/src/assets/css/rssfeeds/app.pcss)
    Error: Loading PostCSS "autoprefixer" plugin failed: Cannot find module 'autoprefixer'
    Require stack:
    - /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/utils.js
    - /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/index.js
    - /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/cjs.js
    - /home/raphy/Raphy-Template/node_modules/loader-runner/lib/loadLoader.js
    - /home/raphy/Raphy-Template/node_modules/loader-runner/lib/LoaderRunner.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/NormalModuleFactory.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/Compiler.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/webpack.js
    - /home/raphy/Raphy-Template/node_modules/webpack/lib/index.js
    - /home/raphy/Raphy-Template/node_modules/webpack-cli/lib/webpack-cli.js
    - /home/raphy/Raphy-Template/node_modules/webpack-cli/lib/bootstrap.js
    - /home/raphy/Raphy-Template/node_modules/webpack-cli/bin/cli.js
    - /home/raphy/Raphy-Template/node_modules/webpack/bin/webpack.js
    
    (@/home/raphy/Raphy-Template/src/assets/css/rssfeeds/app.pcss)
        at loadPlugin (/home/raphy/Raphy-Template/node_modules/postcss-loader/dist/utils.js:117:11)
        at /home/raphy/Raphy-Template/node_modules/postcss-loader/dist/utils.js:212:16
        at Array.map (<anonymous>)
        at getPostcssOptions (/home/raphy/Raphy-Template/node_modules/postcss-loader/dist/utils.js:208:30)
        at Object.loader (/home/raphy/Raphy-Template/node_modules/postcss-loader/dist/index.js:65:42)
     @ ./src/assets/css/rssfeeds/app.pcss 2:12-175 9:17-24 13:15-29
     @ ./src/app/sections/infobasket/Infobasket.tsx 12:0-48
    
    webpack 5.72.0 compiled with 1 error in 29972 ms
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    (base) raphy@pc:~/Raphy-Template$

**Comment by romainmenke** [comment]
That looks like `postcss-loader` trying to run `autoprefixer` but not finding it 🤔.
So now I suspect that this is also passing config in the old style?

No idea how this works as I don't use webpack in this way :/

**Comment by romainmenke** [comment]
Maybe possible to verify this

- rmeove `postcss-preset-env` and `react-scripts`
- manually add `autoprefixer`

Then you will no longer get the error that it's not found.
If you still get the warning we will know that it's not caused by `postcss-preset-env` or `react-scripts`

**Comment by romainmenke** [comment]
Interesting 🤔 

So something (possibly postcss-loader) is automatically running `autoprefixer` and passing along config in an outdated way causing this warning.

Unfortunately this is not something we caused so we can't fix it :/
But maybe `postcss-loader` maintainers can tell you more?

https://github.com/webpack-contrib/postcss-loader

**Comment by raphael10-collab** [comment]
Ok. Thank you. In the meanwhile I'm using this thin trial working fine app : https://github.com/raphael10-collab/PostcssLoaderElectronPlaying as starting point for understanding what in the original app is going on.

You can check yourself
Steps to reproduce:
1) git clone https://github.com/raphael10-collab/PostcssLoaderElectronPlaying
2) cd
3) yarn
4) in one screen yarn type-check
5) in another screen yarn start

**Comment by romainmenke** [comment]
I took a very brief look into the package.json here and with so many dependencies it is impossible to tell if this `postcss-loader` or something else entirely :/

Is it ok if we close this issue here as we confirmed that this is not caused by `postcss-preset-env`?
