### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mitodrummer** [csstools/postcss-plugins#417]
I use postcss-preset-env, and occasionally I will get this error, which never resolves itself and requires a full restart of webpack. It usually happens after saving a css file that contains a reference to a custom media query. my custom media query is defined in a variables.css file, which i pass in via postcss-preset-env

variables.css snippet:
`@custom-media --small-viewport (max-width: 768px);`

webpack.config.js snippet:
```
var postcssPresetEnv = require("postcss-preset-env")({
  stage: 1,
  preserve: false,
  importFrom: [
    "./src/frontend/css/variables.css",
    "./src/frontend/css/colors.css",
    "./src/frontend/css/colors-md.css"
  ]
});
```

snippet from css file that contains the error:
```
@media (--small-viewport) {
  /* .CustomTable .Label {
    display: none;
  } */

  .CustomTable-fixedheader {
    top: var(--navbar-height-small);
  }
  .CustomTable-fixedheader th {
    padding-top: 10px;
  }
  .CustomTable-fixedheader .CustomTable-config {
    top: var(--navbar-height-small);
    right: calc(var(--padding) + 1px);
  }
}
```

TypeError: Cannot read property 'replace' of undefined
at /app/src/frontend/components/CustomTable/styles.css:346:1
at transformMedia (/app/node_modules/postcss-preset-env/node_modules/postcss-custom-media/index.cjs.js:487:23)
at transformMedia (/app/node_modules/postcss-preset-env/node_modules/postcss-custom-media/index.cjs.js:525:38)
at transformMediaList (/app/node_modules/postcss-preset-env/node_modules/postcss-custom-media/index.cjs.js:468:31)
at root.walkAtRules.atrule (/app/node_modules/postcss-preset-env/node_modules/postcss-custom-media/index.cjs.js:569:29)
at /app/node_modules/postcss/lib/container.es6:268:18
at /app/node_modules/postcss/lib/container.es6:110:18
at Root.each (/app/node_modules/postcss/lib/container.es6:76:16)
at Root.walk (/app/node_modules/postcss/lib/container.es6:107:17)
at Root.walkAtRules (/app/node_modules/postcss/lib/container.es6:266:19)
at transformAtrules (/app/node_modules/postcss-preset-env/node_modules/postcss-custom-media/index.cjs.js:566:8)

**Comment by romainmenke** [comment]
@mitodrummer Thank you for this report.

I know it's been a long while but we just took over maintenance and shipped a new version : https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-custom-media/CHANGELOG.md#801-june-3-2022

If there is a chance you could try this version and maybe check if the bug still exists?

**Comment by mitodrummer** [comment]
Un/fortunately the product that I built using postcss was acquired, and will be laid to rest in 2023. 

I will guess that it was a problem because of an antiquated webpack setup, so unless others have run into this issue, it's probably safe to close.

**Comment by romainmenke** [comment]
@mitodrummer Thank you for coming back here to provide some context!
Awesome to hear that your project had a good ending!
